# Generated by Django 2.1.5 on 2019-04-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190421_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
    ]
