# Generated by Django 2.1.5 on 2019-04-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20190421_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id']},
        ),
    ]
