# Generated by Django 2.1.5 on 2019-05-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_label'),
        ('budget', '0006_auto_20190421_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transactions.Transaction')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
