# Generated by Django 2.1.5 on 2019-05-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='budget_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
