# Generated by Django 2.2.4 on 2019-09-08 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_auto_20190901_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='color',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bucket',
            name='icon',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='icon',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='label',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bucket', to='budget.Bucket'),
        ),
    ]
