# Generated by Django 2.2.4 on 2019-09-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_auto_20190908_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
