# Generated by Django 2.2.4 on 2019-09-09 22:08

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_auto_20190908_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.ImageField(upload_to=budget.models.get_file_path),
        ),
    ]
