# Generated by Django 2.2.4 on 2019-09-15 18:28

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_auto_20190909_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_svg_file',
            field=models.FileField(blank=True, null=True, upload_to=budget.models.get_file_path),
        ),
    ]
