# Generated by Django 2.2.4 on 2019-09-16 09:40

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_auto_20190915_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icon',
            name='icon_svg',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='icon_svg_file',
        ),
        migrations.AddField(
            model_name='icon',
            name='icon_object',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=budget.models.get_file_path),
        ),
    ]
