# Generated by Django 2.2.4 on 2019-09-16 09:42

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_auto_20190916_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='icon',
            field=models.FileField(default=1, upload_to=budget.models.get_file_path),
            preserve_default=False,
        ),
    ]
