# Generated by Django 2.2.4 on 2019-09-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_auto_20190916_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icon',
            old_name='icon',
            new_name='icon_svg',
        ),
        migrations.AlterField(
            model_name='label',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icon', to='budget.Icon'),
        ),
    ]
