# Generated by Django 3.0.5 on 2020-04-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20200419_1353'),
        ('budget', '0019_expense_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='expense', serialize=False, to='transactions.Transaction'),
        ),
    ]
