# Generated by Django 2.1.5 on 2019-02-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_transaction', '0002_auto_20190210_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='docfile',
            new_name='upload_file',
        ),
    ]
