# Generated by Django 2.1.5 on 2019-02-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_transaction', '0003_auto_20190210_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='hash_string',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='account',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
