# Generated by Django 2.1.5 on 2019-02-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_mapping'),
        ('import_transaction', '0004_auto_20190210_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='importupload',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account'),
        ),
    ]
