# Generated by Django 2.1.5 on 2019-02-15 17:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190215_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
