# Generated by Django 2.1.5 on 2019-02-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='decimal_sep',
            field=models.CharField(choices=[('.', '.'), (',', ',')], default=',', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='has_negativesign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='thousand_sep',
            field=models.CharField(blank=True, choices=[('.', '.'), (',', ',')], max_length=1, null=True),
        ),
    ]
