# Generated by Django 2.1.5 on 2019-03-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190223_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='decimal_sep',
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_negativesign',
        ),
        migrations.RemoveField(
            model_name='account',
            name='thousand_sep',
        ),
    ]
