# Generated by Django 2.1.5 on 2019-08-01 12:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190315_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('field_map', django.contrib.postgres.fields.jsonb.JSONField()),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
