# Generated by Django 2.1.5 on 2019-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190801_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
