# Generated by Django 2.1.5 on 2019-08-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_provider_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mapping',
        ),
        migrations.AddField(
            model_name='account',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Provider'),
        ),
    ]
