# Generated by Django 2.1.5 on 2019-08-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190801_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='access_type',
            field=models.CharField(choices=[('api', 'API Access'), ('scr', 'Web Scrapping'), ('csv', 'CSV Import')], default='api', max_length=255),
            preserve_default=False,
        ),
    ]
