# Generated by Django 2.2.4 on 2019-08-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_provider_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Account')], default='card', max_length=255),
            preserve_default=False,
        ),
    ]
