# Generated by Django 2.2.4 on 2019-08-04 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_provider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='csv_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
