# Generated by Django 2.2.4 on 2019-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_provider_csv_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='login_sec',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
