# Generated by Django 3.0.5 on 2020-04-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0010_auto_20200405_1459'),
        ('accounts', '0014_auto_20190814_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='csvxls_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importing.CsvXlsImportDetails'),
        ),
    ]
