# Generated by Django 3.0.5 on 2020-04-11 14:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200410_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='csv_meta',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='parser_map',
        ),
        migrations.AlterField(
            model_name='provider',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_image_path),
        ),
    ]
