# Generated by Django 3.0.5 on 2020-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_token_data_token_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_data',
            old_name='expiration_at',
            new_name='expires_at',
        ),
        migrations.AlterField(
            model_name='token_data',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
