# Generated by Django 3.0.5 on 2020-04-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200425_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token_data',
            old_name='token_data',
            new_name='raw_token_data',
        ),
    ]
