# Generated by Django 3.0.5 on 2020-04-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20200425_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token_data',
            options={'ordering': ['-created_at']},
        ),
    ]
