# Generated by Django 3.0.5 on 2020-04-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20200425_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token_data',
            options={'ordering': ['created_at']},
        ),
    ]
