# Generated by Django 3.0.5 on 2020-04-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0014_apiimportdetails'),
        ('accounts', '0025_auto_20200425_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='api_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importing.APIImportDetails'),
        ),
    ]
