# Generated by Django 3.0.5 on 2020-04-30 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0017_importdetails'),
        ('accounts', '0026_provider_api_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='csvxls_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importing.ImportDetails'),
        ),
    ]
