# Generated by Django 3.0.5 on 2020-05-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20200510_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token_data',
            options={'ordering': ['created_at'], 'verbose_name': 'Account Token Data', 'verbose_name_plural': 'Account Token Data'},
        ),
        migrations.AlterField(
            model_name='sub_account',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_account', to='accounts.Account'),
        ),
    ]
