# Generated by Django 3.0.5 on 2020-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200510_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='provider_account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='sub_accounts_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
