# Generated by Django 3.0.5 on 2020-05-14 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0023_auto_20200514_2048'),
        ('accounts', '0032_auto_20200510_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_of_account', to='accounts.Provider'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='import_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_details', to='importing.ImportDetails'),
        ),
    ]
