# Generated by Django 3.0.5 on 2020-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20200514_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sub_account',
            name='sub_account_type',
            field=models.CharField(choices=[('card', 'Card'), ('account', 'Account')], default='account', max_length=255),
            preserve_default=False,
        ),
    ]
