# Generated by Django 3.0.5 on 2020-05-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20200522_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
