# Generated by Django 2.1.5 on 2019-02-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import_transaction', '0005_auto_20190216_1048'),
        ('main', '0002_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='import_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_transaction.ImportUpload'),
        ),
    ]
