# Generated by Django 2.1.5 on 2019-02-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transaction_import_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_curr',
            new_name='account_currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='spending_curr',
            new_name='spending_currency',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user_curr',
            new_name='user_currency',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='country',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hash_duplicate',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='iban',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
