# Generated by Django 2.1.5 on 2019-03-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20190223_0936'),
        # ('import_transaction', '0005_auto_20190216_1048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_original', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('bic', models.CharField(blank=True, max_length=255, null=True)),
                ('counterparty', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('spending_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('spending_currency', models.CharField(max_length=3)),
                ('spending_account_rate', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('account_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('account_currency', models.CharField(max_length=3)),
                ('account_user_rate', models.DecimalField(decimal_places=4, max_digits=1000)),
                ('user_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('user_currency', models.CharField(max_length=3)),
                ('hash_duplicate', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
                # ('import_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='import_transaction.ImportUpload')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
