# Generated by Django 2.1.5 on 2019-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_currency', models.CharField(max_length=3)),
                ('counter_currency', models.CharField(max_length=3)),
            ],
        ),
    ]
