# Generated by Django 2.1.5 on 2019-03-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_fx_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='title_original',
        ),
    ]
