# Generated by Django 2.1.5 on 2019-03-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_title_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit'), ('transfer', 'transfer')], default='credit', max_length=10),
            preserve_default=False,
        ),
    ]
