# Generated by Django 2.1.5 on 2019-04-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20190421_1757'),
        ('transactions', '0006_auto_20190420_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Label'),
        ),
    ]
