# Generated by Django 2.1.5 on 2019-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_transaction_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='purpose',
            new_name='reference_text',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
