# Generated by Django 2.2.4 on 2019-08-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_auto_20190801_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', 'created_at']},
        ),
    ]
