# Generated by Django 2.2.4 on 2019-08-04 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20190804_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fx',
            options={'verbose_name': 'FX Rate', 'verbose_name_plural': 'FX Rates'},
        ),
    ]
