# Generated by Django 2.2.4 on 2019-08-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0001_initial'),
        ('transactions', '0010_auto_20190804_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='import_upload',
        ),
        migrations.AddField(
            model_name='transaction',
            name='importing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importing.NewImport'),
        ),
    ]
