# Generated by Django 2.2.4 on 2019-09-09 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20190818_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label', to='budget.Label'),
        ),
    ]
