# Generated by Django 2.2.4 on 2019-09-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20190909_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='label',
        ),
    ]
