# Generated by Django 3.0.5 on 2020-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0014_remove_transaction_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_user_rate',
            field=models.DecimalField(decimal_places=8, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='spending_account_rate',
            field=models.DecimalField(decimal_places=8, max_digits=1000),
        ),
    ]
