# Generated by Django 3.0.5 on 2020-04-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20200412_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fx',
            name='rate',
            field=models.DecimalField(decimal_places=8, max_digits=1000),
        ),
    ]
