# Generated by Django 3.0.5 on 2020-04-16 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0016_auto_20200412_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.CharField(max_length=255)),
                ('prev_value', models.CharField(max_length=255)),
                ('updated_value', models.CharField(max_length=255)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Change Log',
                'verbose_name_plural': 'Transaction Change Logs',
            },
        ),
    ]
