# Generated by Django 3.0.5 on 2020-04-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_transactionchangelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionChangeLog',
        ),
    ]
