# Generated by Django 3.0.5 on 2020-04-17 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_transactionchangelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction Change Log', 'verbose_name_plural': 'Transaction Change Logs'},
        ),
        migrations.DeleteModel(
            name='TransactionChangeLog',
        ),
    ]
