# Generated by Django 3.0.5 on 2020-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20200417_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionchangelog',
            name='prev_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactionchangelog',
            name='updated_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
