# Generated by Django 3.0.5 on 2020-05-06 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_transaction_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionchangelog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
