# Generated by Django 2.1.5 on 2019-04-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['title']},
        ),
    ]
