# Generated by Django 2.1.5 on 2019-05-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_auto_20190517_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
