# Generated by Django 2.1.5 on 2019-05-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20190517_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='business.Report')),
            ],
        ),
    ]
