# Generated by Django 2.1.5 on 2019-05-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='report',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
