# Generated by Django 2.1.5 on 2019-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='report_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
