# Generated by Django 2.1.5 on 2019-05-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_auto_20190519_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='credit_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='business.Report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('paid-out', 'Paid-out')], default='draft', max_length=10),
        ),
    ]
