# Generated by Django 2.1.5 on 2019-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20190519_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='has_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='has_system',
            field=models.BooleanField(default=False),
        ),
    ]
