# Generated by Django 2.1.5 on 2019-05-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_auto_20190522_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='credit_amount',
            new_name='submit_amount',
        ),
        migrations.AddField(
            model_name='report',
            name='d_payout_submit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='report',
            name='payout_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='report',
            name='payout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
