# Generated by Django 2.2.4 on 2019-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0002_phototan'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototan',
            name='hash_url',
            field=models.CharField(default='eeeee', max_length=255),
            preserve_default=False,
        ),
    ]
