# Generated by Django 2.2.4 on 2019-08-18 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import importing.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190814_1802'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importing', '0003_phototan_hash_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimport',
            name='nmbr_transactions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NewImportOneAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('nmbr_transactions', models.IntegerField(blank=True, null=True)),
                ('raw_csv', models.FileField(blank=True, null=True, upload_to=importing.models.get_file_path)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['imported_at'],
            },
        ),
    ]
