# Generated by Django 2.2.4 on 2019-08-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0005_auto_20190818_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimportoneaccount',
            name='new_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='importing.NewImport'),
        ),
    ]
