# Generated by Django 3.0.5 on 2020-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0007_csvxlsimportdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvxlsimportdetails',
            old_name='sep',
            new_name='csv_sep',
        ),
        migrations.RenameField(
            model_name='csvxlsimportdetails',
            old_name='type',
            new_name='file_type',
        ),
        migrations.RemoveField(
            model_name='csvxlsimportdetails',
            name='first_row',
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='country_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='cutrows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='date_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='date_format',
            field=models.CharField(blank=True, choices=[('%d.%m.%Y', '%d.%m.%Y')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='file_encoding',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='skiprows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='title_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
