# Generated by Django 3.0.5 on 2020-04-05 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0008_auto_20200405_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_amount_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_amount_col_has_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_amount_col_has_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_amount_decimal_sep',
            field=models.CharField(blank=True, choices=[('.', '.'), (',', ','), ("'", "'")], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_amount_thousand_sep',
            field=models.CharField(blank=True, choices=[('.', '.'), (',', ','), ("'", "'")], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_currency_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='account_currency_default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='bic_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='counterparty_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='iban_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='reference_text_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_amount_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_amount_col_has_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_amount_decimal_sep',
            field=models.CharField(blank=True, choices=[('.', '.'), (',', ','), ("'", "'")], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_amount_fallback_to_account_amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_amount_thousand_sep',
            field=models.CharField(blank=True, choices=[('.', '.'), (',', ','), ("'", "'")], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_currency_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='spending_currency_fallback_to_account_currency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='status_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvxlsimportdetails',
            name='status_col_map',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
