# Generated by Django 3.0.5 on 2020-04-10 15:50

from django.db import migrations, models
import importing.models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0010_auto_20200405_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='newimportoneaccount',
            name='parsed_csv',
            field=models.FileField(blank=True, null=True, upload_to=importing.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='csvxlsimportdetails',
            name='date_format',
            field=models.CharField(blank=True, choices=[('%d.%m.%Y', '%d.%m.%Y'), ('%d.%m.%y', '11.03.20')], max_length=10, null=True),
        ),
    ]
