# Generated by Django 3.0.5 on 2020-04-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0011_auto_20200410_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newimport',
            options={'ordering': ['-imported_at'], 'verbose_name': 'Import', 'verbose_name_plural': 'Imports'},
        ),
        migrations.AlterModelOptions(
            name='phototan',
            options={'verbose_name': 'Photo TAN', 'verbose_name_plural': 'Photo TANs'},
        ),
    ]
