# Generated by Django 3.0.5 on 2020-04-30 21:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0014_apiimportdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiimportdetails',
            options={'ordering': ['name'], 'verbose_name': 'API Import Details', 'verbose_name_plural': 'API Import Details'},
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='bic_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='cols_to_drop',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='counterparty_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='iban_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='reference_text_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apiimportdetails',
            name='title_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
