# Generated by Django 3.0.5 on 2020-04-30 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200430_2257'),
        ('importing', '0018_auto_20200430_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIImportDetails',
        ),
        migrations.AlterModelOptions(
            name='importdetails',
            options={'ordering': ['name'], 'verbose_name': 'Import Details', 'verbose_name_plural': 'Import Details'},
        ),
    ]
