# Generated by Django 3.0.5 on 2020-05-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0019_auto_20200430_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='importdetails',
            name='hash_duplicate_col',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='importdetails',
            name='file_type',
            field=models.CharField(blank=True, choices=[('xls', 'XLS'), ('csv', 'CSV'), ('dict', 'DICT')], max_length=10, null=True),
        ),
    ]
