# Generated by Django 3.0.5 on 2020-05-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0021_auto_20200506_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importdetails',
            name='date_format',
            field=models.CharField(blank=True, choices=[('%d.%m.%Y', '%d.%m.%Y'), ('%d.%m.%y', '11.03.20'), ('timestamp_ms', 'timestamp_ms'), ('timestamp', 'timestamp'), ('datetime', 'datetime'), ('%Y-%m-%dT%H:%M:%S.%fZ', '2020-05-05T06:45:19.247Z')], max_length=255, null=True),
        ),
    ]
