# Generated by Django 3.0.5 on 2020-05-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importing', '0022_auto_20200510_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimport',
            name='nmbr_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
